//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BapujiWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_MASTER_TBL
    {
        public long PERSONID { get; set; }
        public string PersonName { get; set; }
        public string PersonAdd1 { get; set; }
        public string PersonAdd2 { get; set; }
        public string PersonCity { get; set; }
        public string PersonState { get; set; }
        public string PersonCountry { get; set; }
        public string PersonPhone1 { get; set; }
        public string PersonPhone2 { get; set; }
        public string PersonEmail1 { get; set; }
        public string PersonEmail2 { get; set; }
    }
}
